service: evira-backed

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  environment:
    MONGODB_URI: ${ssm:/${self:service}/${self:provider.stage}/MONGODB_URI}
    PRODUCT_S3_BUCKET_NAME: ${self:custom.productS3BucketName}
    REGION: ${self:provider.region}

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - secretsmanager:*
          Resource: '*'

        - Effect: 'Allow'
          Action:
            - s3:*
          Resource: '*'

        - Effect: 'Allow'
          Action:
            - sns:*
          Resource:
            - '*'

        - Effect: 'Allow'
          Action:
            - logs:*
          Resource: '*'

        - Effect: 'Allow'
          Action:
            - ssm:*
          Resource: '*'

        - Effect: Allow
          Action:
            - execute-api:Invoke
            - execute-api:ManageConnections
          Resource: 'arn:aws:execute-api:*:*:*'

custom:
  getProductsLambdaArn: !Sub arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:${self:service}-${self:provider.stage}-getProducts
  createProductLambdaArn: !Sub arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:${self:service}-${self:provider.stage}-createProduct
  updateProductByIdLambdaArn: !Sub arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:${self:service}-${self:provider.stage}-updateProductById
  deleteProductByIdLambdaArn: !Sub arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:${self:service}-${self:provider.stage}-deleteProductById
  productS3BucketName: evira-product-images-${opt:stage, self:provider.stage}

appSync: ${file(./resources/appSync.yml)}

functions:
  getProducts:
    handler: functions/products/getProducts.handler
    description: ''
  createProduct:
    handler: functions/products/createProduct.handler
    description: ''
  updateProductById:
    handler: functions/products/updateProductById.handler
    description: ''
  deleteProductById:
    handler: functions/products/deleteProduct.handler
    description: ''

resources:
  Resources:
    productS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.productS3BucketName}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerPreferred

plugins:
  - serverless-appsync-plugin
  - serverless-offline
  - serverless-step-functions
  - serverless-iam-roles-per-function
